### PR TITLE
Eca 31 page inscription

### PR DESCRIPTION
**Pull request by edouardchop**

### CODE REVIEW

**Review by TamWilliam — COMMENTED** [review]
There is a syntax error in your sign-up index page, "@/validator"s.js" instead of "@/validators.js".

**Review by TayZain — COMMENTED** [review]
Your image is incorrectly set because it seems to be tied to the formfield

**Review by TamWilliam — CHANGES_REQUESTED** [review]
Same as ECA 34, components is now located in "src/web/components".

**Review by TamWilliam — CHANGES_REQUESTED** [review]
Sign up route takes back to the same page, why ? It should take you to sign in page, which was the initial route

**Pull request closed without merging**
